#!/bin/bash
#------------------------------------------------------------------------------------------------
# Find Exploit (findxpl.sh)                                                                      |
# Author: Rafael (rlim0x61)                                                                      |
# Date: 04/08/2023 (mm/dd/yyyy)                                                                  |
# Description: reads dpkg -l | rpm -qa output and lists known exploits related to each package.  |
# Usage: ./findxpl.sh [package-list] [Exploit title] ['term|to|be|searched']                     |
# ./findxpl [package-list.txt] ['Privilege Escalation'] ['Linux | Apache 2.4.10']                |
# Version: 1.0.1                                                                                   |
#-------------------------------------------------------------------------------------------------

#BASH COLLORS
RED="\e[91m"
GREEN="\e[92m"
YELLOW="\e[93m"   
BLUE="\e[94m"
BOLDRED="\e[1;${RED}"
BOLDGREEN="\e[1;${GREEN}"
BOLDYELLOW="\e[1;${YELLOW}"
BOLDBLUE="\e[1;${BLUE}"
ENDCOLLOR="\e[0m"

#checks script requirements [TESTED | WORKING]
which searchsploit > /dev/null
if [ $(echo $?) -ne 0 ]
then
   echo ""
   echo -e "[!]${RED}Searchsploit seems to be missing.${ENDCOLLOR}"
   echo ""
   echo "Run: sudo apt-get install exploit-db | yum install exploit-db"
   echo ""
fi
#Uses searchsploit to look for exploits related to a package list generated by DEBIAN [dpkg -l] or CENTOS [rpm -qa]
if [ $# -ne 3 ];
then
   echo ""
   echo -e "${RED}RUN: ./findxpl [package-list.txt] [exploit Title] ['string1 | string2 | stringN']${ENDCOLLOR}"
   echo ""
   echo -e "${GREEN}Example: ./findxpl [package-list.txt] [Privile Escalation] ['linux | Apache 2.4.10']${ENDCOLLOR}"
   echo ""
else
   mkdir exploits
   echo ""
   echo "[Start]"
   echo ""
   echo -e "${BOLDGREEN}[+] Searching for exploits ...${ENDCOLLOR}"
   echo ""
   sleep 2
   for pkg in $(cat $1 | awk '{print $2}');
   do
      searchsploit $pkg -t $2 -w |grep -vE "Shellcodes: No Results|Exploits: No Results" | grep -iE $3 |tee -a exploits/$pkg 2>/dev/null
   done
   #Identify and deletes empty files (file size = 0)
   for emptyFile in `ls -s exploits/ |grep "0" | awk '{print $2}'`;
   do 
   rm -rf exploits/$emptyFile
   done
   #Summary
   exploitsByPackage=`ls -l exploits/ |wc -l`
   totalExploits=`cat exploits/* |wc -l`
   #End banner
   echo ""
   echo "[Summary]"
   echo ""
   echo "|---------------------------------------------------|"
   echo "| [*] Exploit list created at $(pwd)/exploits |"
   echo "|---------------------------------------------------|"
   echo -e "|${BOLDGREEN} [+] Packages with exploits: $exploitsByPackage ${ENDCOLLOR}                    |"
   echo "|---------------------------------------------------|"
   echo -e "|${RED} [++] Total exploits: $totalExploits ${ENDCOLLOR}                           |"
   echo "|---------------------------------------------------|"
   echo ""
   echo "[END]"
fi
